# Generated by Django 2.1.5 on 2020-03-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithms', models.TextField()),
                ('cluster', models.BooleanField()),
                ('log', models.BooleanField()),
                ('graph', models.BooleanField()),
                ('file', models.FileField(upload_to='input/')),
            ],
        ),
        migrations.CreateModel(
            name='OutputData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_file', models.FileField(upload_to='')),
                ('cluster_file', models.FileField(upload_to='')),
                ('log_file', models.FileField(upload_to='')),
            ],
        ),
    ]
