# Generated by Django 2.1.5 on 2020-03-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputdata',
            name='deepLearning',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
