# Generated by Django 2.1.5 on 2020-03-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200324_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='algorithms',
            field=models.CharField(choices=[('AR', 'Auto Regression'), ('ARIMA', 'ARIMA')], max_length=100),
        ),
    ]
