# Generated by Django 2.1.5 on 2020-03-24 19:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20200324_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='algorithms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AR', 'Auto Regression'), ('ARIMA', 'ARIMA')], max_length=8),
        ),
    ]
