# Generated by Django 3.0.5 on 2020-04-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20200403_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='file',
            field=models.FileField(default=None, upload_to='input/'),
        ),
    ]
