# Generated by Django 3.0.5 on 2020-04-07 06:58

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20200404_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputdata',
            name='input_dict',
            field=jsonfield.fields.JSONField(default={'default': 'default'}),
        ),
        migrations.AddField(
            model_name='outputdata',
            name='output_dict',
            field=jsonfield.fields.JSONField(default={'default': 'default'}),
        ),
    ]
