# Generated by Django 3.0.5 on 2020-04-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20200408_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputdata',
            name='email',
            field=models.EmailField(default='dummy@dummy.com', max_length=254),
        ),
    ]
