# Generated by Django 3.0.5 on 2020-04-26 05:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20200426_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 5, 12, 32, 862657, tzinfo=utc)),
        ),
    ]
