class Constants:

    TRAINING_MONTHS = 49
    TESTING_MONTHS = 12
    NUMBER_OF_PREDICTIONS = 12

    ARIMA = "ARIMA"
    MOVING_AVERAGE = "MOVING AVERAGE"
    AR = "AR"
    ARMA = "ARMA"
    SARIMA = "SARIMA"
    SES = "SES"
    RNN = "RNN"
    HWES = "HWES"
    CROSTON = "croston"
    VARMA = "VARMA"
    FNN = "FNN"

    SIMILAR_ALGORITHMS = [ARIMA, MOVING_AVERAGE, AR, ARMA, SARIMA, SES]
    