# Generated by Django 2.1.5 on 2020-03-26 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outputdata',
            name='id',
        ),
        migrations.AddField(
            model_name='outputdata',
            name='input',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.InputData'),
        ),
    ]
