# Generated by Django 2.1.5 on 2020-04-03 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200402_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outputdata',
            old_name='cluster_file',
            new_name='output_file',
        ),
        migrations.RemoveField(
            model_name='outputdata',
            name='forecast_file',
        ),
    ]
