# Generated by Django 2.1.5 on 2020-04-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20200403_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='cluster',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='forecast',
            field=models.BooleanField(null=True),
        ),
    ]
