# Generated by Django 2.1.5 on 2020-04-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20200403_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='file',
            field=models.FileField(blank=True, upload_to='input/'),
        ),
    ]
