# Generated by Django 2.1.5 on 2020-04-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20200403_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='file',
            field=models.FileField(null=True, upload_to='input/'),
        ),
    ]
