# Generated by Django 3.0.5 on 2020-04-26 04:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_userhistory_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 4, 49, 24, 604158, tzinfo=utc)),
        ),
    ]
