# Generated by Django 3.0.5 on 2020-05-05 07:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_auto_20200426_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputdata',
            name='top5_dict',
            field=jsonfield.fields.JSONField(default={'default': 'default'}),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 7, 22, 50, 473025, tzinfo=utc)),
        ),
    ]
