# Generated by Django 3.0.5 on 2020-05-05 11:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_auto_20200505_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputdata',
            name='email',
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 11, 5, 18, 789298, tzinfo=utc)),
        ),
    ]
