# Generated by Django 3.0.5 on 2020-05-05 18:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20200505_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputdata',
            name='int_count',
            field=jsonfield.fields.JSONField(default={'default': 'default'}),
        ),
        migrations.AddField(
            model_name='outputdata',
            name='vol_count',
            field=jsonfield.fields.JSONField(default={'default': 'default'}),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 18, 36, 4, 728442, tzinfo=utc)),
        ),
    ]
